name: Terraform-Deploy-EC2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:

  contents: read

jobs:

  terraform:

    name: Terraform

    runs-on: ubuntu-latest

    environment: production

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:

          aws-access-key-id: ${{ secrets.A }}

          aws-secret-access-key: ${{ secrets.B }}

          aws-session-token: ${{ secrets.C}}

          aws-region: us-east-1

      - name: Terraform Init

        run:  terraform init

      - name: Terraform Plan

        run: terraform plan

#       - name: Terraform Apply

#         run: terraform apply -auto-approve
