name: Terraform-Deploy-EC2

on:
  workflow_dispatch:

permissions:

  contents: read

jobs:

  terraform:

    name: Terraform

    runs-on: ubuntu-latest

    environment: production

    steps:

      - name: Checkout

        uses: actions/checkout@v3

      - name: Setup Terraform

        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials

        uses: aws-actions/configure-aws-credentials@v1

        with:

          aws-access-key-id: ${{ secrets.A }}

          aws-secret-access-key: ${{ secrets.B }}

          aws-session-token: ${{ secrets.C}}

          aws-region: us-east-1

      - name: Terraform Init

        run:

          terraform init

      - name: Terraform Plan

        run: |

          cd deployEC2

          terraform plan

      - name: Terraform Apply

        run: |

          cd deployEC2

          terraform apply -auto-approve
